#!/usr/bin/env python
# Don't run tests from the root repo dir.
# We want to ensure we're importing from the installed
# binary package not from the CWD.

import os
import sys
from subprocess import check_call

_dname = os.path.dirname

sdk_packages = [
    "ask-sdk-runtime", "ask-sdk-core",
    "ask-sdk-dynamodb-persistence-adapter", "ask-sdk"]

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))

for pkg in sdk_packages:
    os.chdir(os.path.join(REPO_ROOT, pkg, "tests"))
    if pkg == "ask-sdk-dynamodb-persistence-adapter":
        pip_pkg_name = "ask_sdk_dynamodb"
    else:
        pip_pkg_name = pkg.replace("-", "_")
    check_call(
        ['nosetests', '--with-coverage', '--cover-erase',
         '--cover-package', pip_pkg_name])