#!/usr/bin/env python
import os
from subprocess import check_call
import shutil

_dname = os.path.dirname

REPO_ROOT = _dname(_dname(_dname(os.path.abspath(__file__))))


def run(command):
    return check_call(command, shell=True)


sdk_packages = [
    "ask-sdk-core", "ask-sdk-dynamodb-persistence-adapter", "ask-sdk"]

for pkg in sdk_packages:
    os.chdir(os.path.join(REPO_ROOT, pkg))
    run("pip install -r requirements.txt")
    if os.path.isdir('dist') and os.listdir('dist'):
        shutil.rmtree('dist')
    run('python setup.py bdist_wheel')
    wheel_dist = os.listdir('dist')[0]
    run('pip install %s' % (os.path.join('dist', wheel_dist)))
